### ISSUE TITLE
Customers

### ISSUE THREAD

**Issue by JudsonStevens** [jude-lawson/rales_engine#1]

**Comment by jude-lawson** [comment]
- [ ] Index
- [ ] Show
- [ ] Single Finders
  - [ ] ID
  - [ ] First Name
  - [ ] Last Name
  - [ ] Created Date
  - [ ] Updated Date
- [ ] Multi Finders
  - [ ] ID
  - [ ] First Name
  - [ ] Last Name
  - [ ] Created Date
  - [ ] Updated Date
- [ ] Random (returns a single random resource)
